import os

DEBUG = True
SECRET_KEY = os.urandom(24)
HOSTNAME='3'
PORT='3306'
USERNAME="root"
PASSWORD="787"
DATABASE='skk'
DB_URL = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URL
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_COMMIT_TEARDOWN = True

